"""add_media_asset_processing_status

Revision ID: 24c3fcd9dbde
Revises: cba038f62af0
Create Date: 2025-10-17 23:53:37.643125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c3fcd9dbde'
down_revision: Union[str, Sequence[str], None] = 'cba038f62af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with default values first
    op.add_column('media_asset', sa.Column('is_processing', sa.Boolean(), nullable=True, default=False))
    op.add_column('media_asset', sa.Column('processing_error', sa.Text(), nullable=True))
    
    # Update existing rows to have default values
    op.execute("UPDATE media_asset SET is_processing = false WHERE is_processing IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('media_asset', 'is_processing', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_asset', 'processing_error')
    op.drop_column('media_asset', 'is_processing')
    # ### end Alembic commands ###
