"""add_processing_run_detection_artifact_tables

Revision ID: 6bbbc0ee84a1
Revises: 7416b48ea5ac
Create Date: 2025-10-18 14:01:49.449594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bbbc0ee84a1'
down_revision: Union[str, Sequence[str], None] = '7416b48ea5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('homography_session_id', sa.UUID(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['homography_session_id'], ['homography_session.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('jsonl_detections', 'csv_detections', 'annotated_video', 'report', 'debug')", name='artifact_kind_check'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('frame_idx', sa.Integer(), nullable=False),
    sa.Column('t_ms', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('cls', sa.String(), nullable=False),
    sa.Column('conf', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('wx', sa.Float(), nullable=True),
    sa.Column('wy', sa.Float(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('detection_frame_idx', 'detection', ['frame_idx'], unique=False)
    op.create_index('detection_project_time_idx', 'detection', ['project_id', 't_ms'], unique=False)
    op.create_index('detection_project_track_idx', 'detection', ['project_id', 'track_id'], unique=False)
    op.create_index('detection_run_idx', 'detection', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('detection_run_idx', table_name='detection')
    op.drop_index('detection_project_track_idx', table_name='detection')
    op.drop_index('detection_project_time_idx', table_name='detection')
    op.drop_index('detection_frame_idx', table_name='detection')
    op.drop_table('detection')
    op.drop_table('artifact')
    op.drop_table('processing_run')
    # ### end Alembic commands ###
