"""add_homography_tables

Revision ID: 7416b48ea5ac
Revises: 24c3fcd9dbde
Create Date: 2025-10-18 11:58:03.560478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7416b48ea5ac'
down_revision: Union[str, Sequence[str], None] = '24c3fcd9dbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homography_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('screenshot_asset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screenshot_asset_id'], ['media_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homography_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('matrix_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reprojection_error', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['homography_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homography_pair',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('image_x_norm', sa.Float(), nullable=False),
    sa.Column('image_y_norm', sa.Float(), nullable=False),
    sa.Column('map_lat', sa.Float(), nullable=False),
    sa.Column('map_lng', sa.Float(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['homography_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homography_pair')
    op.drop_table('homography_model')
    op.drop_table('homography_session')
    # ### end Alembic commands ###
