"""add_video_start_time_to_media_asset

Revision ID: 9813b0a82f66
Revises: 6bbbc0ee84a1
Create Date: 2025-10-18 23:45:01.967452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9813b0a82f66'
down_revision: Union[str, Sequence[str], None] = '6bbbc0ee84a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_asset', sa.Column('video_start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_asset', 'video_start_time')
    # ### end Alembic commands ###
