"""add_llm_analysis_table

Revision ID: 99c0089b0283
Revises: ea93a3e5b81a
Create Date: 2025-10-20 12:22:42.205738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99c0089b0283'
down_revision: Union[str, Sequence[str], None] = 'ea93a3e5b81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('track_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index('idx_llm_analysis_analysis_id', 'llm_analysis', ['analysis_id'], unique=False)
    op.create_index('idx_llm_analysis_project_id', 'llm_analysis', ['project_id'], unique=False)
    op.create_index('idx_llm_analysis_run_id', 'llm_analysis', ['run_id'], unique=False)
    op.create_index('idx_llm_analysis_status', 'llm_analysis', ['status'], unique=False)
    op.add_column('report', sa.Column('llm_analysis_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'report', 'llm_analysis', ['llm_analysis_id'], ['id'], ondelete='SET NULL')
    op.drop_column('report', 'analysis_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('analysis_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'llm_analysis_id')
    op.drop_index('idx_llm_analysis_status', table_name='llm_analysis')
    op.drop_index('idx_llm_analysis_run_id', table_name='llm_analysis')
    op.drop_index('idx_llm_analysis_project_id', table_name='llm_analysis')
    op.drop_index('idx_llm_analysis_analysis_id', table_name='llm_analysis')
    op.drop_table('llm_analysis')
    # ### end Alembic commands ###
