// This file is auto-generated by @hey-api/openapi-ts

export const AnalysisListResponseSchema = {
    properties: {
        analyses: {
            items: {
                '$ref': '#/components/schemas/AnalysisResponse'
            },
            type: 'array',
            title: 'Analyses'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['analyses', 'total'],
    title: 'AnalysisListResponse',
    description: 'Response model for analysis list.'
} as const;

export const AnalysisResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        run_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Run Id'
        },
        analysis_id: {
            type: 'string',
            title: 'Analysis Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        result_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Result Data'
        },
        track_ids: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Track Ids'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'run_id', 'analysis_id', 'status', 'result_data', 'track_ids', 'created_at', 'completed_at', 'error_message'],
    title: 'AnalysisResponse',
    description: 'Response model for LLM analysis data.'
} as const;

export const ArtifactPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid4',
            title: 'Id'
        },
        kind: {
            type: 'string',
            title: 'Kind'
        },
        uri: {
            type: 'string',
            title: 'Uri'
        },
        meta: {
            additionalProperties: true,
            type: 'object',
            title: 'Meta'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'kind', 'uri', 'meta', 'created_at'],
    title: 'ArtifactPublic'
} as const;

export const ArtifactsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArtifactPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ArtifactsPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_projects_update_video_start_timeSchema = {
    properties: {
        video_start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Start Time'
        }
    },
    type: 'object',
    title: 'Body_projects-update_video_start_time'
} as const;

export const Body_projects_upload_videoSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        video_start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Start Time'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_projects-upload_video'
} as const;

export const DetectionPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        frame_idx: {
            type: 'integer',
            title: 'Frame Idx'
        },
        t_ms: {
            type: 'integer',
            title: 'T Ms'
        },
        track_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Track Id'
        },
        cls: {
            type: 'string',
            title: 'Cls'
        },
        conf: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conf'
        },
        x: {
            type: 'number',
            title: 'X'
        },
        y: {
            type: 'number',
            title: 'Y'
        },
        w: {
            type: 'number',
            title: 'W'
        },
        h: {
            type: 'number',
            title: 'H'
        },
        wx: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wx'
        },
        wy: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wy'
        },
        extra: {
            additionalProperties: true,
            type: 'object',
            title: 'Extra'
        }
    },
    type: 'object',
    required: ['id', 'frame_idx', 't_ms', 'track_id', 'cls', 'conf', 'x', 'y', 'w', 'h', 'wx', 'wy', 'extra'],
    title: 'DetectionPublic'
} as const;

export const DetectionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DetectionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DetectionsPublic'
} as const;

export const FilterDetectionsRequestSchema = {
    properties: {
        track_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Track Ids'
        },
        artifact_id: {
            type: 'string',
            title: 'Artifact Id'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        }
    },
    type: 'object',
    required: ['track_ids', 'artifact_id'],
    title: 'FilterDetectionsRequest',
    description: 'Request model for filtering detections by track IDs.'
} as const;

export const FilterDetectionsResponseSchema = {
    properties: {
        artifact_id: {
            type: 'string',
            title: 'Artifact Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        track_count: {
            type: 'integer',
            title: 'Track Count'
        },
        detection_count: {
            type: 'integer',
            title: 'Detection Count'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['artifact_id', 'filename', 'track_count', 'detection_count', 'message'],
    title: 'FilterDetectionsResponse',
    description: 'Response model for filtered detections.'
} as const;

export const GenerateReportRequestSchema = {
    properties: {
        llm_analysis_id: {
            type: 'string',
            title: 'Llm Analysis Id'
        },
        run_id: {
            type: 'string',
            title: 'Run Id'
        }
    },
    type: 'object',
    required: ['llm_analysis_id', 'run_id'],
    title: 'GenerateReportRequest',
    description: 'Request model for generating a PDF report.'
} as const;

export const GenerateReportResponseSchema = {
    properties: {
        report_id: {
            type: 'string',
            title: 'Report Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['report_id', 'status', 'message'],
    title: 'GenerateReportResponse',
    description: 'Response model for generating a PDF report.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HomographyModelPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        matrix_data: {
            items: {
                items: {
                    type: 'number'
                },
                type: 'array'
            },
            type: 'array',
            title: 'Matrix Data'
        },
        reprojection_error: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reprojection Error'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        meta: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Meta'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'matrix_data', 'reprojection_error', 'created_at', 'meta'],
    title: 'HomographyModelPublic',
    description: 'Schema for homography model response'
} as const;

export const HomographyPairCreateSchema = {
    properties: {
        image_x_norm: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Image X Norm',
            description: 'Normalized x coordinate (0-1)'
        },
        image_y_norm: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Image Y Norm',
            description: 'Normalized y coordinate (0-1)'
        },
        map_lat: {
            type: 'number',
            title: 'Map Lat',
            description: 'Latitude coordinate'
        },
        map_lng: {
            type: 'number',
            title: 'Map Lng',
            description: 'Longitude coordinate'
        },
        order_idx: {
            type: 'integer',
            title: 'Order Idx',
            description: 'Display order index',
            default: 0
        }
    },
    type: 'object',
    required: ['image_x_norm', 'image_y_norm', 'map_lat', 'map_lng'],
    title: 'HomographyPairCreate',
    description: 'Schema for creating a homography point pair'
} as const;

export const HomographyPairPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        image_x_norm: {
            type: 'number',
            title: 'Image X Norm'
        },
        image_y_norm: {
            type: 'number',
            title: 'Image Y Norm'
        },
        map_lat: {
            type: 'number',
            title: 'Map Lat'
        },
        map_lng: {
            type: 'number',
            title: 'Map Lng'
        },
        order_idx: {
            type: 'integer',
            title: 'Order Idx'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'image_x_norm', 'image_y_norm', 'map_lat', 'map_lng', 'order_idx'],
    title: 'HomographyPairPublic',
    description: 'Schema for homography point pair response'
} as const;

export const HomographySessionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        screenshot_asset_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Screenshot Asset Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        solved_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solved At'
        },
        pairs: {
            items: {
                '$ref': '#/components/schemas/HomographyPairPublic'
            },
            type: 'array',
            title: 'Pairs',
            default: []
        },
        model: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/HomographyModelPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'screenshot_asset_id', 'status', 'created_at', 'solved_at'],
    title: 'HomographySessionPublic',
    description: 'Schema for homography session response'
} as const;

export const HomographySolveResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        model: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/HomographyModelPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'HomographySolveResponse',
    description: 'Schema for homography solve response'
} as const;

export const MediaAssetPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        kind: {
            type: 'string',
            title: 'Kind'
        },
        uri: {
            type: 'string',
            title: 'Uri'
        },
        bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bytes'
        },
        meta: {
            additionalProperties: true,
            type: 'object',
            title: 'Meta'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        is_processing: {
            type: 'boolean',
            title: 'Is Processing',
            default: false
        },
        processing_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Error'
        },
        video_start_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Start Time'
        },
        presigned_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Presigned Url',
            description: 'Generate presigned URL for S3 objects.',
            readOnly: true
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'kind', 'uri', 'bytes', 'meta', 'created_at', 'presigned_url'],
    title: 'MediaAssetPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProcessingRunCreateSchema = {
    properties: {
        params: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params',
            default: {}
        }
    },
    type: 'object',
    title: 'ProcessingRunCreate'
} as const;

export const ProcessingRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid4',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid4',
            title: 'Project Id'
        },
        homography_session_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid4'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Homography Session Id'
        },
        params: {
            additionalProperties: true,
            type: 'object',
            title: 'Params'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            additionalProperties: true,
            type: 'object',
            title: 'Progress'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'homography_session_id', 'params', 'status', 'progress', 'started_at', 'finished_at', 'error_message'],
    title: 'ProcessingRunPublic'
} as const;

export const ProcessingRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProcessingRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProcessingRunsPublic'
} as const;

export const ProjectCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ProjectCreate'
} as const;

export const ProjectLocationCreateSchema = {
    properties: {
        addr_line: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Addr Line'
        },
        lat: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lat'
        },
        lon: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lon'
        },
        source: {
            type: 'string',
            maxLength: 50,
            title: 'Source',
            default: 'user'
        }
    },
    type: 'object',
    title: 'ProjectLocationCreate'
} as const;

export const ProjectLocationPublicSchema = {
    properties: {
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        addr_line: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Addr Line'
        },
        lat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lat'
        },
        lon: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lon'
        },
        source: {
            type: 'string',
            title: 'Source'
        }
    },
    type: 'object',
    required: ['project_id', 'addr_line', 'lat', 'lon', 'source'],
    title: 'ProjectLocationPublic'
} as const;

export const ProjectPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        video_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        video: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaAssetPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        location: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectLocationPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        media_assets: {
            items: {
                '$ref': '#/components/schemas/MediaAssetPublic'
            },
            type: 'array',
            title: 'Media Assets',
            default: []
        },
        homography_session: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/HomographySessionPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title', 'id', 'user_id', 'video_id', 'created_at'],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const ReportListResponseSchema = {
    properties: {
        reports: {
            items: {
                '$ref': '#/components/schemas/ReportResponse'
            },
            type: 'array',
            title: 'Reports'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['reports', 'total'],
    title: 'ReportListResponse',
    description: 'Response model for report list.'
} as const;

export const ReportResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        run_id: {
            type: 'string',
            title: 'Run Id'
        },
        llm_analysis_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Llm Analysis Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        pdf_uri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pdf Uri'
        },
        meta: {
            additionalProperties: true,
            type: 'object',
            title: 'Meta'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['id', 'project_id', 'run_id', 'llm_analysis_id', 'status', 'pdf_uri', 'meta', 'created_at', 'completed_at'],
    title: 'ReportResponse',
    description: 'Response model for report data.'
} as const;

export const StartAnalysisRequestSchema = {
    properties: {
        run_id: {
            type: 'string',
            title: 'Run Id'
        }
    },
    type: 'object',
    required: ['run_id'],
    title: 'StartAnalysisRequest',
    description: 'Request model for starting LLM analysis.'
} as const;

export const StartAnalysisResponseSchema = {
    properties: {
        analysis_id: {
            type: 'string',
            title: 'Analysis Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['analysis_id', 'status', 'message'],
    title: 'StartAnalysisResponse',
    description: 'Response model for starting LLM analysis.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['id', 'email', 'is_active', 'is_superuser', 'full_name'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const src__common__features__project__schemas__MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;