// This file is auto-generated by @hey-api/openapi-ts

export type ArtifactPublic = {
    id: string;
    kind: string;
    uri: string;
    meta: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type ArtifactsPublic = {
    data: Array<ArtifactPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_projects_update_video_start_time = {
    video_start_time?: (string | null);
};

export type Body_projects_upload_video = {
    file: (Blob | File);
    video_start_time?: (string | null);
};

export type DetectionPublic = {
    id: number;
    frame_idx: number;
    t_ms: number;
    track_id: (number | null);
    cls: string;
    conf: (number | null);
    x: number;
    y: number;
    w: number;
    h: number;
    wx: (number | null);
    wy: (number | null);
    extra: {
        [key: string]: unknown;
    };
};

export type DetectionsPublic = {
    data: Array<DetectionPublic>;
    count: number;
};

/**
 * Request model for filtering detections by track IDs.
 */
export type FilterDetectionsRequest = {
    track_ids: Array<(number)>;
    artifact_id: string;
    filename?: (string | null);
};

/**
 * Response model for filtered detections.
 */
export type FilterDetectionsResponse = {
    artifact_id: string;
    filename: string;
    track_count: number;
    detection_count: number;
    message: string;
};

/**
 * Request model for generating a PDF report.
 */
export type GenerateReportRequest = {
    analysis_id: string;
    run_id: string;
};

/**
 * Response model for generating a PDF report.
 */
export type GenerateReportResponse = {
    report_id: string;
    status: string;
    message: string;
};

/**
 * Schema for homography model response
 */
export type HomographyModelPublic = {
    id: string;
    session_id: string;
    matrix_data: Array<Array<(number)>>;
    reprojection_error: (number | null);
    created_at: string;
    meta: ({
    [key: string]: unknown;
} | null);
};

/**
 * Schema for creating a homography point pair
 */
export type HomographyPairCreate = {
    /**
     * Normalized x coordinate (0-1)
     */
    image_x_norm: number;
    /**
     * Normalized y coordinate (0-1)
     */
    image_y_norm: number;
    /**
     * Latitude coordinate
     */
    map_lat: number;
    /**
     * Longitude coordinate
     */
    map_lng: number;
    /**
     * Display order index
     */
    order_idx?: number;
};

/**
 * Schema for homography point pair response
 */
export type HomographyPairPublic = {
    id: string;
    session_id: string;
    image_x_norm: number;
    image_y_norm: number;
    map_lat: number;
    map_lng: number;
    order_idx: number;
};

/**
 * Schema for homography session response
 */
export type HomographySessionPublic = {
    id: string;
    project_id: string;
    screenshot_asset_id: (string | null);
    status: string;
    created_at: string;
    solved_at: (string | null);
    pairs?: Array<HomographyPairPublic>;
    model?: (HomographyModelPublic | null);
};

/**
 * Schema for homography solve response
 */
export type HomographySolveResponse = {
    success: boolean;
    model?: (HomographyModelPublic | null);
    error_message?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MediaAssetPublic = {
    id: string;
    project_id: string;
    kind: string;
    uri: string;
    bytes: (number | null);
    meta: {
        [key: string]: unknown;
    };
    created_at: string;
    is_processing?: boolean;
    processing_error?: (string | null);
    video_start_time?: (string | null);
    /**
     * Generate presigned URL for S3 objects.
     */
    readonly presigned_url: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProcessingRunCreate = {
    params?: ({
    [key: string]: unknown;
} | null);
};

export type ProcessingRunPublic = {
    id: string;
    project_id: string;
    homography_session_id: (string | null);
    params: {
        [key: string]: unknown;
    };
    status: string;
    progress: {
        [key: string]: unknown;
    };
    started_at: string;
    finished_at: (string | null);
    error_message: (string | null);
};

export type ProcessingRunsPublic = {
    data: Array<ProcessingRunPublic>;
    count: number;
};

export type ProjectCreate = {
    title: string;
    description?: (string | null);
};

export type ProjectLocationCreate = {
    addr_line?: (string | null);
    lat?: (number | null);
    lon?: (number | null);
    source?: string;
};

export type ProjectLocationPublic = {
    project_id: string;
    addr_line: (string | null);
    lat: (number | null);
    lon: (number | null);
    source: string;
};

export type ProjectPublic = {
    title: string;
    description?: (string | null);
    id: string;
    user_id: string;
    video_id: (string | null);
    created_at: string;
    video?: (MediaAssetPublic | null);
    location?: (ProjectLocationPublic | null);
    media_assets?: Array<MediaAssetPublic>;
    homography_session?: (HomographySessionPublic | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Response model for report list.
 */
export type ReportListResponse = {
    reports: Array<ReportResponse>;
    total: number;
};

/**
 * Response model for report data.
 */
export type ReportResponse = {
    id: string;
    project_id: string;
    run_id: string;
    analysis_id: string;
    status: string;
    pdf_uri: (string | null);
    meta: {
        [key: string]: unknown;
    };
    created_at: string;
    completed_at: (string | null);
};

export type src__common__features__project__schemas__Message = {
    message: string;
};

/**
 * Request model for starting LLM analysis.
 */
export type StartAnalysisRequest = {
    run_id: string;
};

/**
 * Response model for starting LLM analysis.
 */
export type StartAnalysisResponse = {
    analysis_id: string;
    status: string;
    message: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
};

export type UserPublic = {
    id: string;
    email: string;
    is_active: boolean;
    is_superuser: boolean;
    full_name: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LlmAnalysisStartLlmAnalysisData = {
    projectId: string;
    requestBody: StartAnalysisRequest;
};

export type LlmAnalysisStartLlmAnalysisResponse = (StartAnalysisResponse);

export type LlmAnalysisOptionsLlmAnalysisStreamData = {
    analysisId: string;
    projectId: string;
};

export type LlmAnalysisOptionsLlmAnalysisStreamResponse = (unknown);

export type LlmAnalysisStreamLlmAnalysisEventsData = {
    analysisId: string;
    projectId: string;
    /**
     * Authentication token for SSE connection
     */
    token?: string;
};

export type LlmAnalysisStreamLlmAnalysisEventsResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (src__common__features__project__schemas__Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsCreateProjectRouteData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectRouteResponse = (ProjectPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectRouteData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectRouteResponse = (ProjectPublic);

export type ProjectsDeleteProjectRouteData = {
    projectId: string;
};

export type ProjectsDeleteProjectRouteResponse = (src__common__features__project__schemas__Message);

export type ProjectsUploadVideoData = {
    formData: Body_projects_upload_video;
    projectId: string;
};

export type ProjectsUploadVideoResponse = (MediaAssetPublic);

export type ProjectsGetMediaPresignedUrlData = {
    mediaAssetId: string;
    projectId: string;
};

export type ProjectsGetMediaPresignedUrlResponse = (unknown);

export type ProjectsUpdateVideoStartTimeData = {
    formData?: Body_projects_update_video_start_time;
    mediaAssetId: string;
    projectId: string;
};

export type ProjectsUpdateVideoStartTimeResponse = (MediaAssetPublic);

export type ProjectsSetProjectLocationData = {
    projectId: string;
    requestBody: ProjectLocationCreate;
};

export type ProjectsSetProjectLocationResponse = (ProjectLocationPublic);

export type ProjectsExtractVideoFrameData = {
    projectId: string;
};

export type ProjectsExtractVideoFrameResponse = (MediaAssetPublic);

export type ProjectsCreateHomographySessionData = {
    projectId: string;
};

export type ProjectsCreateHomographySessionResponse = (HomographySessionPublic);

export type ProjectsGetHomographySessionData = {
    projectId: string;
};

export type ProjectsGetHomographySessionResponse = (HomographySessionPublic);

export type ProjectsAddHomographyPairData = {
    requestBody: HomographyPairCreate;
    sessionId: string;
};

export type ProjectsAddHomographyPairResponse = (HomographyPairPublic);

export type ProjectsUpdateHomographyPairsData = {
    requestBody: Array<HomographyPairCreate>;
    sessionId: string;
};

export type ProjectsUpdateHomographyPairsResponse = (Array<HomographyPairPublic>);

export type ProjectsDeleteHomographyPairData = {
    pairId: string;
};

export type ProjectsDeleteHomographyPairResponse = (unknown);

export type ProjectsSolveHomographySessionData = {
    sessionId: string;
};

export type ProjectsSolveHomographySessionResponse = (HomographySolveResponse);

export type ProjectsGetHomographyModelData = {
    sessionId: string;
};

export type ProjectsGetHomographyModelResponse = (HomographyModelPublic);

export type ProjectsExportHomographySessionData = {
    sessionId: string;
};

export type ProjectsExportHomographySessionResponse = (unknown);

export type ProjectsStartProcessingData = {
    projectId: string;
    requestBody: ProcessingRunCreate;
};

export type ProjectsStartProcessingResponse = (ProcessingRunPublic);

export type ProjectsListProcessingRunsRouteData = {
    projectId: string;
};

export type ProjectsListProcessingRunsRouteResponse = (ProcessingRunsPublic);

export type ProjectsGetProcessingRunRouteData = {
    runId: string;
};

export type ProjectsGetProcessingRunRouteResponse = (ProcessingRunPublic);

export type ProjectsGetDetectionsRouteData = {
    frameIdx?: (number | null);
    limit?: number;
    runId: string;
    skip?: number;
};

export type ProjectsGetDetectionsRouteResponse = (DetectionsPublic);

export type ProjectsGetDetectionsByFrameRouteData = {
    frameIdx: number;
    runId: string;
};

export type ProjectsGetDetectionsByFrameRouteResponse = (DetectionsPublic);

export type ProjectsGenerateAnnotatedVideoRouteData = {
    runId: string;
};

export type ProjectsGenerateAnnotatedVideoRouteResponse = (ArtifactPublic);

export type ProjectsListArtifactsRouteData = {
    runId: string;
};

export type ProjectsListArtifactsRouteResponse = (ArtifactsPublic);

export type ProjectsGetArtifactDownloadUrlData = {
    artifactId: string;
};

export type ProjectsGetArtifactDownloadUrlResponse = ({
    [key: string]: unknown;
});

export type ProjectsGetArtifactContentData = {
    artifactId: string;
};

export type ProjectsGetArtifactContentResponse = (unknown);

export type ReportsGenerateReportData = {
    projectId: string;
    requestBody: GenerateReportRequest;
};

export type ReportsGenerateReportResponse = (GenerateReportResponse);

export type ReportsListReportsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type ReportsListReportsResponse = (ReportListResponse);

export type ReportsGetReportDetailsData = {
    projectId: string;
    reportId: string;
};

export type ReportsGetReportDetailsResponse = (ReportResponse);

export type ReportsDownloadReportData = {
    projectId: string;
    reportId: string;
};

export type ReportsDownloadReportResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserRouteData = {
    requestBody: UserCreate;
};

export type UsersCreateUserRouteResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeRouteResponse = (src__common__features__project__schemas__Message);

export type UsersUpdateUserMeRouteData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeRouteResponse = (UserPublic);

export type UsersUpdatePasswordMeRouteData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeRouteResponse = (src__common__features__project__schemas__Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserRouteData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserRouteResponse = (UserPublic);

export type UsersDeleteUserRouteData = {
    userId: string;
};

export type UsersDeleteUserRouteResponse = (src__common__features__project__schemas__Message);

export type VideoAnnotationFilterDetectionsByTracksData = {
    requestBody: FilterDetectionsRequest;
};

export type VideoAnnotationFilterDetectionsByTracksResponse = (FilterDetectionsResponse);

export type VideoAnnotationGetFilteredArtifactDownloadUrlData = {
    artifactId: string;
};

export type VideoAnnotationGetFilteredArtifactDownloadUrlResponse = ({
    [key: string]: unknown;
});