// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_projects_upload_video = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MediaAssetPublic = {
    id: string;
    project_id: string;
    kind: string;
    uri: string;
    bytes: (number | null);
    meta: {
        [key: string]: unknown;
    };
    created_at: string;
    is_processing?: boolean;
    processing_error?: (string | null);
    /**
     * Generate presigned URL for S3 objects.
     */
    readonly presigned_url: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    title: string;
    description?: (string | null);
};

export type ProjectLocationCreate = {
    addr_line?: (string | null);
    lat?: (number | null);
    lon?: (number | null);
    source?: string;
};

export type ProjectLocationPublic = {
    project_id: string;
    addr_line: (string | null);
    lat: (number | null);
    lon: (number | null);
    source: string;
};

export type ProjectPublic = {
    title: string;
    description?: (string | null);
    id: string;
    user_id: string;
    video_id: (string | null);
    created_at: string;
    video?: (MediaAssetPublic | null);
    location?: (ProjectLocationPublic | null);
    media_assets?: Array<MediaAssetPublic>;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type src__common__features__project__schemas__Message = {
    message: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
};

export type UserPublic = {
    id: string;
    email: string;
    is_active: boolean;
    is_superuser: boolean;
    full_name: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (src__common__features__project__schemas__Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsCreateProjectRouteData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectRouteResponse = (ProjectPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectRouteData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectRouteResponse = (ProjectPublic);

export type ProjectsDeleteProjectRouteData = {
    projectId: string;
};

export type ProjectsDeleteProjectRouteResponse = (src__common__features__project__schemas__Message);

export type ProjectsUploadVideoData = {
    formData: Body_projects_upload_video;
    projectId: string;
};

export type ProjectsUploadVideoResponse = (MediaAssetPublic);

export type ProjectsGetMediaPresignedUrlData = {
    mediaAssetId: string;
    projectId: string;
};

export type ProjectsGetMediaPresignedUrlResponse = (unknown);

export type ProjectsSetProjectLocationData = {
    projectId: string;
    requestBody: ProjectLocationCreate;
};

export type ProjectsSetProjectLocationResponse = (ProjectLocationPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserRouteData = {
    requestBody: UserCreate;
};

export type UsersCreateUserRouteResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeRouteResponse = (src__common__features__project__schemas__Message);

export type UsersUpdateUserMeRouteData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeRouteResponse = (UserPublic);

export type UsersUpdatePasswordMeRouteData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeRouteResponse = (src__common__features__project__schemas__Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserRouteData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserRouteResponse = (UserPublic);

export type UsersDeleteUserRouteData = {
    userId: string;
};

export type UsersDeleteUserRouteResponse = (src__common__features__project__schemas__Message);